language: node_js
node_js:
  - "10.15"
branches:
  only:
  - development # auto build and deploy in only development branch
  - master # auto build and deploy in only master branch
install:
  - yarn

script:
  - yarn lint
  - yarn build:production