export const mutationType = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  VERIFY_SIGNUP: "VERIFY_SIGNUP",
  REQUEST_OTP: "REQUEST_OTP",
  CONFIRM_OTP: "CONFIRM_OTP",
  CONFIRM_PROFILE: "CONFIRM_PROFILE",
  CREATE_DEFAULT_CLOUDFIREWALL: "CREATE_DEFAULT_CLOUDFIREWALL",
  ROLES: "ROLES",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  EMAIL: "EMAIL",
  RESEND_EMAIL: "RESEND_EMAIL"
};
