export const mutationType = {
  LOADING: "LOADING",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  SET_SNACKBAR: "SET_SNACKBAR",
  SET_MODALHANDLER: "SET_MODALHANDLER",
  SET_ACTIONHANDLER: "SET_ACTIONHANDLER",
  SET_ACTIONTYPEHANDLER: "SET_ACTIONTYPEHANDLER"
};
